### ISSUE TITLE
Packages for Ubuntu:10.04 No Longer Available

### ISSUE THREAD

**Issue by KedneckInc** [AndrewKvalheim/treemaker#1]
I'm presently trying to build the docker container that you provided (THANKS!) and found that the packages for 10.04 are no longer available.  I've switched the ubuntu version to 14.04, and it appears to be building okay at this time.  More Later.

**Comment by KedneckInc** [comment]
No luck.  Same issue I ran into, "OpenGL libraries not available."  When the compile attempts to run anyway it can't seem to find the 'build/release/**/*.dep' files' then "fatal error: wx/statline.h: No such file or directory".  Sigh.

**Comment by AndrewKvalheim** [comment]
Thanks for the head-up. The package repositories for end-of-life releases are [archived][old-releases] under a different namespace. I've updated the image to use that instead.

  [old-releases]: https://askubuntu.com/q/91815/1859

**Comment by KedneckInc** [comment]
Many thanks!  Builds and works just fine now.
