### ISSUE TITLE
Build Image fails on curl to get and unzip wxWindows

### ISSUE THREAD

**Issue by akhilpanchal** [AndrewKvalheim/treemaker#2]
Hi:
Thanks for such a helpful utility!.

I am trying to build the docker container, and I get this error on the curl command that fetches and unzips wxwindows:
```sh
 => ERROR [4/11] RUN curl --location          http://downloads.sourceforge.net/project/wxwindows/2.6.4/wxGTK-2.6.4.tar.bz2     | tar --extract --bzip2 --directory   0.9s
------
 > [4/11] RUN curl --location          http://downloads.sourceforge.net/project/wxwindows/2.6.4/wxGTK-2.6.4.tar.bz2     | tar --extract --bzip2 --directory /tmp:
#7 0.387   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#7 0.390                                  Dload  Upload   Total   Spent    Left  Speed
117   353  117   353    0     0   1542      0 --:--:-- --:--:-- --:--:--  3460
#7 0.895 curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
#7 0.899
#7 0.899 bzip2: Compressed file ends unexpectedly;
#7 0.899 	perhaps it is corrupted?  *Possible* reason follows.
#7 0.899 bzip2: Inappropriate ioctl for device
#7 0.899 	Input file = (stdin), output file = (stdout)
#7 0.899
#7 0.899 It is possible that the compressed file(s) have become corrupted.
#7 0.899 You can use the -tvv option to test integrity of such files.
#7 0.899
#7 0.899 You can use the `bzip2recover' program to attempt to recover
#7 0.899 data from undamaged sections of corrupted files.
```
Is anyone else seeing this as well?

**Comment by AndrewKvalheim** [comment]
Thanks, looks like the SourceForge CDN now requires TLS 1.2, which isn't supported by that old version of cURL. I've moved the download to the host system instead.

**Comment by akhilpanchal** [comment]
Thanks a lot @AndrewKvalheim for looking into this.
The image builds fine now.
However, I am getting 

```sh
./docker_run_x: line 5: tempfile: command not found
```
on running the `./docker_run_x --rm treemaker --help` command.
I installed X Server for MacOS from https://www.xquartz.org/.
Is there a step that I am missing? Any help on this would be great.

**Comment by AndrewKvalheim** [comment]
Thanks for all the testing. :) Turns out `tempfile` is [typically](https://github.com/koalaman/shellcheck/wiki/SC2186) only available on Debian-based systems. I've [replaced](https://github.com/AndrewKvalheim/treemaker/commit/dd3fbbd27761e70785ac8dace8feae64e3828733) that with `mktemp`, which should be more portable.

That said, I don't have a macOS system myself so there might be more adjustments you'll have to make for your environment. [These answers](https://stackoverflow.com/q/16296753) were a useful resource for me when getting this to work on Ubuntu, and I see some macOS-specific advice there as well.

**Comment by akhilpanchal** [comment]
I was able to get it working by following [this answer](https://stackoverflow.com/a/36190462) on the StackOverflow thread that you shared.
Thanks again @AndrewKvalheim!.

PS: Updated script for anyone who might be trying to run this on OSX

### Prereq:
* Install [X11](https://www.xquartz.org/)
* Install `socat` by running `brew install socat`

### Updated wrapper for OSX
```sh
#!/usr/bin/env bash

CONTAINER=treemaker
COMMAND=/bin/bash
NIC=en0

# Grab the ip address of this box
IPADDR=$(ifconfig $NIC | grep "inet " | awk '{print $2}')

DISP_NUM=$(jot -r 1 100 200)  # random display number between 100 and 200
PORT_NUM=$((6000 + DISP_NUM)) # so multiple instances of the container won't interfer with eachother

socat TCP-LISTEN:${PORT_NUM},reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" 2>&1 > /dev/null &

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth.$USER.$$
touch $XAUTH
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

docker run \
    -it \
    --rm \
    -v $XSOCK:$XSOCK:rw \
    -v $XAUTH:$XAUTH:rw \
    -e DISPLAY=$IPADDR:$DISP_NUM \
    -e XAUTHORITY=$XAUTH \
    $CONTAINER \
    $COMMAND

rm -f $XAUTH
kill %1       # kill the socat job launched above
```

**Comment by akhilpanchal** [comment]
@AndrewKvalheim 
If you feel it would be valuable to add this wrapper for OSX to this project and a note in the README, I'll be happy to submit a PR.
